[package]
name = "duckair"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "duckair"
path = "main.rs"

[[bin]]
name = "data_types"
path = "02_data_types/main.rs"

[[bin]]
name = "variables"
path = "03_variables/main.rs"
