[package]
name = "publish_demo_luispdm"
version = "0.0.2"
edition = "2021"
description = "Pluralsight demo project"
license = "Apache-2.0"
repository = "https://github.com/luispdm/duckair"

[dependencies]
rand = "0.8.5"

[[bin]]
name = "demo"
path = "main.rs"
